# Link Demo

We demo 2 different functions for collecting link data from Wikipedia:
1. `get_links` - for collecting different types of links from a list of pages.
2. `pipeline_get_links` - A convenience wrapper function that, in addition to the above, also sets up session and redirect maps.

## Setup

In [1]:
import wikitoolkit
import pandas as pd

my_agent = 'mwapi testing <p.gildersleve@exeter.ac.uk>'
wtsession = wikitoolkit.WTSession('en.wikipedia', user_agent=my_agent)
toparts = pd.read_csv('data/topviews-2024_07_31.csv')
artlist = toparts['Page'].unique().tolist() # ~1000 top articles yesterday

## `get_links`

This can be used to collect in-, out-, interwiki-, lang-, and external links to/from a list of articles.

### Out-links

In [2]:
outlinks = await wikitoolkit.get_links(wtsession, mode='out', titles=artlist[:10])
edges = pd.DataFrame(set([(k, x['title']) for k, v in outlinks.items() for x in v]),
            columns=['source', 'target'])
edges

Warning: No PageMaps object provided, this is not recommended practice
Getting out-links

                    source                                             target
0            Katie Ledecky                              Diane Guthrie-Gresham
1               Sunisa Lee                Romania at the 1984 Summer Olympics
2               Sunisa Lee  Gymnastics at the 1968 Summer Olympics – Women...
3     2024 Summer Olympics               Zimbabwe at the 2024 Summer Olympics
4               Sunisa Lee          1999 NCAA Women's Gymnastics Championship
...                    ...                                                ...
9966  2024 Summer Olympics  Triathlon at the 2024 Summer Olympics – Qualif...
9967         Kamala Harris                                          Tim Kaine
9968          Simone Biles                  Gymnastics at the Summer Olympics
9969         Kamala Harris                                      Isabel Guzman
9970         Kamala Harris                        Selma to Montgomery marches

[9971 rows x 2 columns]

### External links

In [3]:
extlinks = await wikitoolkit.get_links(wtsession, mode=['ext'], titles=artlist[:10])
edges = pd.DataFrame([{'source': k, 'target': x['url']}for k, v in extlinks.items()
                      for x in v], columns=['source', 'target'])
edges

Warning: No PageMaps object provided, this is not recommended practice
Getting ext-links

              source                                             target
0      Kamala Harris  https://x.com/KamalaHarris/status/735197253153...
1      Kamala Harris  https://www.mercurynews.com/2020/08/18/heres-k...
2      Kamala Harris  https://www.mercurynews.com/2017/12/06/kamala-...
3      Kamala Harris  https://www.mercurynews.com/2019/08/01/democra...
4      Kamala Harris  https://web.archive.org/web/20210217084253/htt...
...              ...                                                ...
3571  Jonathan Owens  https://www.nbcnewyork.com/news/sports/nfl/sim...
3572  Jonathan Owens  https://www.usatoday.com/story/sports/nfl/2024...
3573  Jonathan Owens  https://www.espn.com/nfl/story?id=41179488&_sl...
3574  Jonathan Owens  https://archive.today/20240909185841/https://w...
3575  Jonathan Owens  https://archive.today/20240909190224/https://w...

[3576 rows x 2 columns]

### All kinds of link

In [4]:
alllinks = await wikitoolkit.get_links(wtsession, mode=['in', 'out', 'lang',
                                                          'interwiki', 'ext'],
                                     titles=artlist[:10])

# Create a dataframe for each type of link
wikiedges = pd.DataFrame(set([(k, x['title']) for k, v in alllinks['out'].items()
                              for x in v] +
                             [(x['title'], k) for k, v in alllinks['in'].items()
                              for x in v]), columns=['source', 'target'])
extedges = pd.DataFrame([{'source': k, 'target': x['url']}
                         for k, v in alllinks['ext'].items() for x in v])
interwikiedges = pd.concat({k: pd.DataFrame(v) for k, v in alllinks['interwiki'].items()}
                            ).reset_index(drop=True, level=1).reset_index(
                            ).rename(columns={'index': 'source',
                                              'prefix': 'target_prefix',
                                              'title': 'target_title'})
langedges = pd.concat({k: pd.DataFrame(v).T for k, v in alllinks['lang'].items()}
                     ).reset_index().rename(columns={'level_0': 'source',
                                                     'level_1': 'target_lang',
                                                     0: 'target_title'})

display(wikiedges.head(), extedges.head(), interwikiedges.head(), langedges.head())

Warning: No PageMaps object provided, this is not recommended practice
Getting in-links
Getting out-links
Getting lang-links
Getting interwiki-links
Getting ext-links

,source,target
0,Peter Evans (swimmer),Michael Phelps
1,Shang-Chi (Marvel Cinematic Universe),Deadpool & Wolverine
2,Ketanji Brown Jackson,Kamala Harris
3,Sunisa Lee,Gymnastics at the 1968 Summer Olympics – Women...
4,2024 Summer Olympics,Zimbabwe at the 2024 Summer Olympics

          source                                             target
0  Kamala Harris  https://x.com/KamalaHarris/status/735197253153...
1  Kamala Harris  https://www.mercurynews.com/2020/08/18/heres-k...
2  Kamala Harris  https://www.mercurynews.com/2017/12/06/kamala-...
3  Kamala Harris  https://www.mercurynews.com/2019/08/01/democra...
4  Kamala Harris  https://web.archive.org/web/20210217084253/htt...

          source target_prefix            target_title
0  Kamala Harris             c  Category:Kamala_Harris
1  Kamala Harris       commons  Category:Kamala_Harris
2  Kamala Harris             d               Q10853588
3  Kamala Harris             n  Category:Kamala_Harris
4  Kamala Harris             q           Kamala_Harris

          source target_lang   target_title
0  Kamala Harris          af  Kamala Harris
1  Kamala Harris         als  Kamala Harris
2  Kamala Harris          an  Kamala Harris
3  Kamala Harris          ar   كامالا هاريس
4  Kamala Harris         arz   كامالا هاريس

## `pipeline_get_links`

This function sets up the session, fixes redirects with PageMaps (see `redirectsdemo.ipynb`), and collects link data. It is a convenience function that wraps the previous function. Note that this does not require manual setup of the `wtsession`.

In [5]:
links, pagemaps = await wikitoolkit.pipeline_get_links('en.wikipedia', my_agent,
                                                titles=artlist[:10],
                                                gl_args={'mode':['out', 'in'],
                                                        'update_maps':True})

# Get list of articles and edges (excluding redlinks, those with no page id)
articles = set([x['title'] for y in links['in'].values() for x in y] +
                [x['title'] for y in links['out'].values() for x in y
                 if pagemaps.id_map[x['title']] != -1])
edges = pd.DataFrame(set([(k, x['title']) for k, v in links['out'].items()
                          for x in v if pagemaps.id_map[x['title']] != -1] +
                         [(x['title'], k) for k, v in links['in'].items()
                          for x in v]), columns=['source', 'target'])

# Additionally returns new pagemaps object (if not supplied), storing redirects, normalizations, and page ids
# It's recommended to create a single pagemaps object in a project and update it with each call
print(pagemaps)

print(len(articles), len(edges))
display(edges.head())

Getting out-links
Getting in-links
Redirects: 1087, Norms: 0, IDs: 19979, Existing: 0
18892 27334

,source,target
0,Peter Evans (swimmer),Michael Phelps
1,Shang-Chi (Marvel Cinematic Universe),Deadpool & Wolverine
2,Ketanji Brown Jackson,Kamala Harris
3,Sunisa Lee,Gymnastics at the 1968 Summer Olympics – Women...
4,2024 Summer Olympics,Zimbabwe at the 2024 Summer Olympics

In [6]:
# testing with page ids instead of titles
ids = [pagemaps.id_map[x] for x in artlist[:10]]
# supply pre-existing pagemaps object
links = await wikitoolkit.pipeline_get_links('en.wikipedia', my_agent,
                                                pageids=ids, pagemaps=pagemaps,
                                                gl_args={'mode':['out', 'in',
                                                                 'lang', 'ext',
                                                                 'interwiki'],
                                                        'update_maps':True})
print(pagemaps)
print(len(links['in']), len(links['out']), len(links['lang']),
        len(links['ext']), len(links['interwiki']))

Getting out-links
Getting in-links
Getting lang-links
Getting ext-links
Getting interwiki-links
Redirects: 1087, Norms: 0, IDs: 19979, Existing: 0
10 10 10 10 10

### Redirect demo

The pipeline function can also fix redirects / normalize titles as part of the process. The redirect has to be recorded on Wikipedia, it can't magically fix typos.

In [7]:
bad_titles = [x.lower() for x in artlist[:10]] + ['thisisnotatitle']
links = await wikitoolkit.pipeline_get_links('en.wikipedia', my_agent,
                                                titles=bad_titles, pagemaps=pagemaps,
                                                gl_args={'mode':['out', 'in'],
                                                        'update_maps':True})

# Get list of articles and edges (excluding redlinks, those with no page id)
articles = set([x['title'] for y in links['in'].values() for x in y] +
                [x['title'] for y in links['out'].values() for x in y
                 if pagemaps.id_map[x['title']] != -1])
edges = pd.DataFrame(set([(k, x['title']) for k, v in links['out'].items()
                          for x in v if pagemaps.id_map[x['title']] != -1] +
                         [(x['title'], k) for k, v in links['in'].items()
                          for x in v]), columns=['source', 'target'])

# has updated pagemaps object inplace with norms/redirects/pageids
print(pagemaps)

print(len(articles), len(edges))
display(edges.head())

Getting out-links
Getting in-links
Redirects: 1095, Norms: 10, IDs: 19987, Existing: 0
8013 11045

                                              source          target
0  List of United States presidential candidates ...   Kamala Harris
1                                  2024 in Australia  Ismail Haniyeh
2                                Views of Kanye West   Kamala Harris
3                              Peter Evans (swimmer)  Michael Phelps
4                            Stephen Milne (swimmer)  Michael Phelps

## Large scale collection

The functions can be used to collect data on a large scale asyncronously, with adaptations around any rate limiting. Here we demonstrate collecting data on 1000 random articles. In-link collection is particularly slow for popular articles as so many other articles link to them.

In [8]:
links, pagemaps = await wikitoolkit.pipeline_get_links('en.wikipedia', my_agent,
                                                titles=artlist,
                                                gl_args={'mode':['out', 'in'],
                                                        'update_maps':True})

# Get list of articles and edges (excluding redlinks, those with no page id)
articles = set([x['title'] for y in links['in'].values() for x in y] +
                [x['title'] for y in links['out'].values() for x in y
                 if pagemaps.id_map[x['title']] != -1])
edges = pd.DataFrame(set([(k, x['title']) for k, v in links['out'].items()
                          for x in v if pagemaps.id_map[x['title']] != -1] +
                         [(x['title'], k) for k, v in links['in'].items()
                          for x in v]), columns=['source', 'target'])

print(len(articles), len(edges))
display(edges.head())

Getting out-links
Getting in-links
2619852 6291673

                         source          target
0                Annerys Vargas      Azerbaijan
1  Inauguration of Javier Milei   United States
2              Jan D. Achenbach  George W. Bush
3                         Titus    Roman Senate
4              Makaracı, Amasra          Turkey

In [9]:
# I have a hunch that ordering the articles by number of (in-)links
# will make collection of articles more efficient for subsequent API calls.
# Let's try it

top_indegree = edges['target'].value_counts()
ordered_artlist = ([x for x in top_indegree.index if x in artlist] +
                   [x for x in artlist if x not in top_indegree.index])[::-1]
ordered_artlist[-10:] # These articles have loooots of in-links, v slow to collect

new_links, new_pagemaps = await wikitoolkit.pipeline_get_links('en.wikipedia', my_agent,
                                                titles=ordered_artlist,
                                                gl_args={'mode':['out', 'in'],
                                                        'update_maps':True})

# Get list of articles and edges (excluding redlinks, those with no page id)
new_articles = set([x['title'] for y in new_links['in'].values() for x in y] +
                [x['title'] for y in new_links['out'].values() for x in y
                 if new_pagemaps.id_map[x['title']] != -1])
new_edges = set([(k, x['title']) for k, v in new_links['out'].items() 
                 for x in v if new_pagemaps.id_map[x['title']] != -1] +
                [(x['title'], k) for k, v in new_links['in'].items()
                for x in v])

print(len(new_articles), len(new_edges))

Getting out-links
Getting in-links
Max retries exceeded for query: {'titles': 'Iran', 'generator': 'linkshere', 'glhlimit': 'max', 'redirects': True, 'glhnamespace': '0'}
80.97% complete
Trying again at n=800 with batchsize=100
Increasing batchsize to 200
Max retries exceeded for query: {'titles': '2012 Summer Olympics', 'generator': 'linkshere', 'glhlimit': 'max', 'redirects': True, 'glhnamespace': '0'}
91.09% complete
Trying again at n=900 with batchsize=100
Max retries exceeded for query: {'titles': '2020 Summer Olympics', 'generator': 'linkshere', 'glhlimit': 'max', 'redirects': True, 'glhnamespace': '0'}
91.09% complete
Trying again at n=900 with batchsize=50
Increasing batchsize to 100
Max retries exceeded for query: {'titles': 'Indonesia', 'generator': 'linkshere', 'glhlimit': 'max', 'redirects': True, 'glhnamespace': '0'}
96.15% complete
Trying again at n=950 with batchsize=50
Max retries exceeded for query: {'titles': 'Taiwan', 'generator': 'linkshere', 'glhlimit': 'max', 'redirects': True, 'glhnamespace': '0'}
96.15% complete
Trying again at n=950 with batchsize=25
Increasing batchsize to 50
Increasing batchsize to 100
2619859 6291707