# Pageviews Demo

We demo 2 different functions for collecting revisions data from Wikipedia:
1. `api_article_views` - for collecting daily/monthly pageviews data from the API for a list of articles.
2. `pipeline_api_article_views` - A convenience wrapper function that, in addition to the above, also sets up client/session and redirect maps.

## Setup

In [1]:
import wikitoolkit
import pandas as pd

my_agent = 'mwapi testing <p.gildersleve@exeter.ac.uk>'
wtsession = wikitoolkit.WTSession('en.wikipedia', user_agent=my_agent)

toparts = pd.read_csv('data/topviews-2024_07_31.csv')
artlist = toparts['Page'].unique().tolist() # ~1000 top articles yesterday

## `api_article_views`

In [2]:
pageviews = await wikitoolkit.api_article_views(wtsession, 'en.wikipedia', artlist[:10])
pd.DataFrame(pageviews).T.head()

Warning: Redirects requested but no pagemaps provided. Redirects will not be found and combined.

,Simone Biles,Ismail Haniyeh,2024 Summer Olympics,Kamala Harris,Deadpool & Wolverine,Katie Ledecky,Sunisa Lee,MyKayla Skinner,Jonathan Owens,Michael Phelps
2024-12-04,3484,1357,5891,15957,20635,1062,3660,111,694,2091
2024-12-05,3593,1269,6271,15847,20331,878,1752,95,706,2874
2024-12-06,3164,1333,6209,14688,22016,805,1570,110,1289,2863
2024-12-07,2951,1341,5834,12809,27893,806,1532,99,608,2453
2024-12-08,3371,2278,5524,12658,28013,865,1282,131,980,2246

## `pipeline_api_article_views`

This function sets up the session/client, fixes redirects with PageMaps, and collects pageview data. It is a convenience function that wraps the previous function. Note that this does not require manual setup of the `wtsession`. Observe that the figures are slightly higher than the previous example, due to the inclusion of pageviews for the redirects.

In [3]:
pageviews_p, pagemaps = await wikitoolkit.pipeline_api_article_views('en.wikipedia', my_agent,
                                                        artlist[:10])
# Additionally returns new pagemaps object (if not supplied), storing redirects, normalizations, and page ids
# It's recommended to create a single pagemaps object in a project and update it with each call
print(pagemaps)
pd.DataFrame(pageviews_p).T.head()

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1077d2ea0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1115add90>, 360812.192915125), (<aiohttp.client_proto.ResponseHandler object at 0x1115adf70>, 360812.193709666), (<aiohttp.client_proto.ResponseHandler object at 0x1115aeab0>, 360812.194688625), (<aiohttp.client_proto.ResponseHandler object at 0x1115aee70>, 360812.195641708), (<aiohttp.client_proto.ResponseHandler object at 0x1115aec90>, 360812.196609375), (<aiohttp.client_proto.ResponseHandler object at 0x1115ae330>, 360812.197390583), (<aiohttp.client_proto.ResponseHandler object at 0x1115ae8d0>, 360812.198386583), (<aiohttp.client_proto.ResponseHandler object at 0x1115ae510>, 360812.199218625), (<aiohttp.client_proto.ResponseHandler object at 0x1115ae6f0>, 360812.20015275), (<aiohttp.client_proto.ResponseHandler object at 0x1115af050>, 360812.201174958), (<aiohttp.client_proto.ResponseHandler object at 0x1115af230>, 360812.202114375), (<aiohttp.client_proto.ResponseHandler object at 0x1115af410>, 360812.202846875), (<aiohttp.client_proto.ResponseHandler object at 0x1115af7d0>, 360812.203721208), (<aiohttp.client_proto.ResponseHandler object at 0x1115af5f0>, 360812.204563416), (<aiohttp.client_proto.ResponseHandler object at 0x1115af9b0>, 360812.205516625), (<aiohttp.client_proto.ResponseHandler object at 0x1115afd70>, 360812.206393125), (<aiohttp.client_proto.ResponseHandler object at 0x1115afb90>, 360812.207161208), (<aiohttp.client_proto.ResponseHandler object at 0x1115aff50>, 360812.208249541), (<aiohttp.client_proto.ResponseHandler object at 0x1113f0ad0>, 360812.20913), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4170>, 360812.210044458), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4350>, 360812.210817375), (<aiohttp.client_proto.ResponseHandler object at 0x1115c48f0>, 360812.212318875), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4530>, 360812.2126115), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4710>, 360812.213539333), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4ad0>, 360812.214355166), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4cb0>, 360812.215190541), (<aiohttp.client_proto.ResponseHandler object at 0x1113f1970>, 360812.216542916), (<aiohttp.client_proto.ResponseHandler object at 0x1113f2450>, 360812.217421833), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4e90>, 360812.218332166), (<aiohttp.client_proto.ResponseHandler object at 0x1113f1670>, 360812.219166083), (<aiohttp.client_proto.ResponseHandler object at 0x1113f1c10>, 360812.220009), (<aiohttp.client_proto.ResponseHandler object at 0x1113f28d0>, 360812.220779125), (<aiohttp.client_proto.ResponseHandler object at 0x1113f1490>, 360812.221922291), (<aiohttp.client_proto.ResponseHandler object at 0x1113f2e70>, 360812.223124708), (<aiohttp.client_proto.ResponseHandler object at 0x1113f3230>, 360812.223932083), (<aiohttp.client_proto.ResponseHandler object at 0x1113f1790>, 360812.224822125), (<aiohttp.client_proto.ResponseHandler object at 0x1113f26f0>, 360812.225557291), (<aiohttp.client_proto.ResponseHandler object at 0x1113f21b0>, 360812.2264865), (<aiohttp.client_proto.ResponseHandler object at 0x1113f2ab0>, 360812.227417041), (<aiohttp.client_proto.ResponseHandler object at 0x1113f3410>, 360812.228710916), (<aiohttp.client_proto.ResponseHandler object at 0x1113f1fd0>, 360812.229808333), (<aiohttp.client_proto.ResponseHandler object at 0x1113f3050>, 360812.230632708), (<aiohttp.client_proto.ResponseHandler object at 0x1113f35f0>, 360812.231440791), (<aiohttp.client_proto.ResponseHandler object at 0x1113f1df0>, 360812.232350791), (<aiohttp.client_proto.ResponseHandler object at 0x1113f3b90>, 360812.23325425), (<aiohttp.client_proto.ResponseHandler object at 0x1113f2c90>, 360812.234083458), (<aiohttp.client_proto.ResponseHandler object at 0x1113f39b0>, 360812.23537825), (<aiohttp.client_proto.ResponseHandler object at 0x1113f3f50>, 360812.2362885), (<aiohttp.client_proto.ResponseHandler object at 0x1113f3d70>, 360812.237164666), (<aiohttp.client_proto.ResponseHandler object at 0x11159c350>, 360812.238000208), (<aiohttp.client_proto.ResponseHandler object at 0x11159d070>, 360812.23889125), (<aiohttp.client_proto.ResponseHandler object at 0x11159c530>, 360812.239765666), (<aiohttp.client_proto.ResponseHandler object at 0x11159dd90>, 360812.240635333), (<aiohttp.client_proto.ResponseHandler object at 0x11159c710>, 360812.241462583), (<aiohttp.client_proto.ResponseHandler object at 0x11159dbb0>, 360812.243689708), (<aiohttp.client_proto.ResponseHandler object at 0x11159d430>, 360812.244557791), (<aiohttp.client_proto.ResponseHandler object at 0x11159d610>, 360812.246004708), (<aiohttp.client_proto.ResponseHandler object at 0x11159c8f0>, 360812.246439416), (<aiohttp.client_proto.ResponseHandler object at 0x11159cad0>, 360812.247389333), (<aiohttp.client_proto.ResponseHandler object at 0x1113f37d0>, 360812.24827775), (<aiohttp.client_proto.ResponseHandler object at 0x11159c170>, 360812.249376125), (<aiohttp.client_proto.ResponseHandler object at 0x11159ccb0>, 360812.250244958), (<aiohttp.client_proto.ResponseHandler object at 0x11159ce90>, 360812.251296), (<aiohttp.client_proto.ResponseHandler object at 0x11159d250>, 360812.252112875), (<aiohttp.client_proto.ResponseHandler object at 0x11159e8d0>, 360812.253032666), (<aiohttp.client_proto.ResponseHandler object at 0x11159e150>, 360812.2538235), (<aiohttp.client_proto.ResponseHandler object at 0x11159df70>, 360812.254739208), (<aiohttp.client_proto.ResponseHandler object at 0x11159e330>, 360812.258483458), (<aiohttp.client_proto.ResponseHandler object at 0x11159e6f0>, 360812.259369666), (<aiohttp.client_proto.ResponseHandler object at 0x11159eab0>, 360812.260304708), (<aiohttp.client_proto.ResponseHandler object at 0x11159e510>, 360812.261638458), (<aiohttp.client_proto.ResponseHandler object at 0x11159ee70>, 360812.263447041), (<aiohttp.client_proto.ResponseHandler object at 0x11159ec90>, 360812.26376475), (<aiohttp.client_proto.ResponseHandler object at 0x11159d7f0>, 360812.264711916), (<aiohttp.client_proto.ResponseHandler object at 0x11159f050>, 360812.265527458), (<aiohttp.client_proto.ResponseHandler object at 0x11159f410>, 360812.270899625), (<aiohttp.client_proto.ResponseHandler object at 0x11159d9d0>, 360812.272963041), (<aiohttp.client_proto.ResponseHandler object at 0x11159f5f0>, 360812.273798291), (<aiohttp.client_proto.ResponseHandler object at 0x11159f230>, 360812.274567541), (<aiohttp.client_proto.ResponseHandler object at 0x11159f9b0>, 360812.275434666), (<aiohttp.client_proto.ResponseHandler object at 0x11159f7d0>, 360812.276181083), (<aiohttp.client_proto.ResponseHandler object at 0x11159fb90>, 360812.276986541), (<aiohttp.client_proto.ResponseHandler object at 0x11159fd70>, 360812.277728333), (<aiohttp.client_proto.ResponseHandler object at 0x1115ac170>, 360812.27852825), (<aiohttp.client_proto.ResponseHandler object at 0x1115ac350>, 360812.279262), (<aiohttp.client_proto.ResponseHandler object at 0x11159ff50>, 360812.280930375), (<aiohttp.client_proto.ResponseHandler object at 0x1115ac710>, 360812.284462416), (<aiohttp.client_proto.ResponseHandler object at 0x1115ac530>, 360812.285279833), (<aiohttp.client_proto.ResponseHandler object at 0x1115accb0>, 360812.286003), (<aiohttp.client_proto.ResponseHandler object at 0x1115ac8f0>, 360812.286915333), (<aiohttp.client_proto.ResponseHandler object at 0x1115ace90>, 360812.287708125), (<aiohttp.client_proto.ResponseHandler object at 0x1115acad0>, 360812.288547791), (<aiohttp.client_proto.ResponseHandler object at 0x1115ad070>, 360812.28932375), (<aiohttp.client_proto.ResponseHandler object at 0x1115ad250>, 360812.290113625), (<aiohttp.client_proto.ResponseHandler object at 0x1115ad7f0>, 360812.2908515), (<aiohttp.client_proto.ResponseHandler object at 0x1115ad610>, 360812.291677583), (<aiohttp.client_proto.ResponseHandler object at 0x1115ad430>, 360812.295277541), (<aiohttp.client_proto.ResponseHandler object at 0x1115ad9d0>, 360812.296074208), (<aiohttp.client_proto.ResponseHandler object at 0x1115ae150>, 360812.298945291), (<aiohttp.client_proto.ResponseHandler object at 0x1115adbb0>, 360812.299698125)]']
connector: <aiohttp.connector.TCPConnector object at 0x110ecf1a0>

Redirects: 192, Norms: 0, IDs: 192, Existing: 10

,Simone Biles,Ismail Haniyeh,2024 Summer Olympics,Kamala Harris,Deadpool & Wolverine,Katie Ledecky,Sunisa Lee,MyKayla Skinner,Jonathan Owens,Michael Phelps
2024-12-04,3485,1401,6078,16199,20822,1066,3705,116,694,2300
2024-12-05,3596,1296,6424,16039,20453,878,1798,99,706,3058
2024-12-06,3165,1356,6420,14852,22116,805,1628,112,1289,3054
2024-12-07,2951,1376,5984,12986,28022,807,1589,105,608,2657
2024-12-08,3371,2305,5734,12840,28137,865,1337,134,980,2398

In [4]:
# Demo that views from redirects can be considerable!

rd_max_increase = (pd.DataFrame(pageviews_p).T/pd.DataFrame(pageviews).T).max().max()
rd_max_increase_ix1 = (pd.DataFrame(pageviews_p).T/pd.DataFrame(pageviews).T).max().idxmax()
rd_max_increase_ix2 = (pd.DataFrame(pageviews_p).T/pd.DataFrame(pageviews).T
                        ).max(axis=1).idxmax().strftime('%Y-%m-%d')
print(f"Max increase in pageviews from redirects ={(rd_max_increase-1)*100:.2f}% for {rd_max_increase_ix1} on {rd_max_increase_ix2}")

Max increase in pageviews from redirects =16.53% for Sunisa Lee on 2025-01-01

In [5]:
# call function with pagemaps object supplied
pageviews_old = await wikitoolkit.pipeline_api_article_views('en.wikipedia', my_agent,
                                                        artlist[10:20], pagemaps=pagemaps,
                                                        aav_args={'start':'20170701',
                                                                 'end':'20170731'})

# pagemaps object is updated with new redirects and normalizations
print(pagemaps)
display(pd.DataFrame(pageviews_old).T.head())

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1154cc350>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1111a7b90>, 360813.685207416), (<aiohttp.client_proto.ResponseHandler object at 0x1111a79b0>, 360813.68599975), (<aiohttp.client_proto.ResponseHandler object at 0x1111a7f50>, 360813.687123583), (<aiohttp.client_proto.ResponseHandler object at 0x111333530>, 360813.688028916), (<aiohttp.client_proto.ResponseHandler object at 0x1113330b0>, 360813.689310833), (<aiohttp.client_proto.ResponseHandler object at 0x1113329f0>, 360813.698942041), (<aiohttp.client_proto.ResponseHandler object at 0x1111a7d70>, 360813.699895291), (<aiohttp.client_proto.ResponseHandler object at 0x1113313d0>, 360813.70065), (<aiohttp.client_proto.ResponseHandler object at 0x111332f90>, 360813.702655791), (<aiohttp.client_proto.ResponseHandler object at 0x111331d90>, 360813.703448291), (<aiohttp.client_proto.ResponseHandler object at 0x111333b90>, 360813.704406375), (<aiohttp.client_proto.ResponseHandler object at 0x111332210>, 360813.705346958), (<aiohttp.client_proto.ResponseHandler object at 0x111331fd0>, 360813.706114041), (<aiohttp.client_proto.ResponseHandler object at 0x111331e50>, 360813.709770875), (<aiohttp.client_proto.ResponseHandler object at 0x111330b90>, 360813.710669791), (<aiohttp.client_proto.ResponseHandler object at 0x111330d10>, 360813.711556375), (<aiohttp.client_proto.ResponseHandler object at 0x111331670>, 360813.712551125), (<aiohttp.client_proto.ResponseHandler object at 0x1113322d0>, 360813.713456083), (<aiohttp.client_proto.ResponseHandler object at 0x111332630>, 360813.714390333), (<aiohttp.client_proto.ResponseHandler object at 0x111331eb0>, 360813.71535775), (<aiohttp.client_proto.ResponseHandler object at 0x1113317f0>, 360813.716288083), (<aiohttp.client_proto.ResponseHandler object at 0x111330ef0>, 360813.717160791), (<aiohttp.client_proto.ResponseHandler object at 0x111333110>, 360813.718158583), (<aiohttp.client_proto.ResponseHandler object at 0x111331070>, 360813.719197375), (<aiohttp.client_proto.ResponseHandler object at 0x111331610>, 360813.720088333), (<aiohttp.client_proto.ResponseHandler object at 0x111331850>, 360813.721084958), (<aiohttp.client_proto.ResponseHandler object at 0x111330770>, 360813.722055083), (<aiohttp.client_proto.ResponseHandler object at 0x111330230>, 360813.722839208), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4650>, 360813.723774583), (<aiohttp.client_proto.ResponseHandler object at 0x111331250>, 360813.72483725), (<aiohttp.client_proto.ResponseHandler object at 0x1115c45f0>, 360813.7256655), (<aiohttp.client_proto.ResponseHandler object at 0x1115c57f0>, 360813.726675916), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4c50>, 360813.727512291), (<aiohttp.client_proto.ResponseHandler object at 0x1115c7bf0>, 360813.728293166), (<aiohttp.client_proto.ResponseHandler object at 0x1115c7cb0>, 360813.729259666), (<aiohttp.client_proto.ResponseHandler object at 0x111330170>, 360813.730171708), (<aiohttp.client_proto.ResponseHandler object at 0x111330530>, 360813.730991875), (<aiohttp.client_proto.ResponseHandler object at 0x1115c6690>, 360813.731966291), (<aiohttp.client_proto.ResponseHandler object at 0x111330950>, 360813.73282525), (<aiohttp.client_proto.ResponseHandler object at 0x1115c65d0>, 360813.733619041), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4410>, 360813.7345815), (<aiohttp.client_proto.ResponseHandler object at 0x1115c5af0>, 360813.735317333), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4050>, 360813.738319541), (<aiohttp.client_proto.ResponseHandler object at 0x1115c5490>, 360813.739256708), (<aiohttp.client_proto.ResponseHandler object at 0x1115c40b0>, 360813.740167958), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4dd0>, 360813.741098625), (<aiohttp.client_proto.ResponseHandler object at 0x1115c6390>, 360813.742093458), (<aiohttp.client_proto.ResponseHandler object at 0x1115c59d0>, 360813.743167416), (<aiohttp.client_proto.ResponseHandler object at 0x1115c5d90>, 360813.744023458), (<aiohttp.client_proto.ResponseHandler object at 0x1115c55b0>, 360813.744951666), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4a10>, 360813.745707583), (<aiohttp.client_proto.ResponseHandler object at 0x1115c4830>, 360813.746518208), (<aiohttp.client_proto.ResponseHandler object at 0x1115c6bd0>, 360813.747534666), (<aiohttp.client_proto.ResponseHandler object at 0x1115c6510>, 360813.748308041), (<aiohttp.client_proto.ResponseHandler object at 0x1115c6c90>, 360813.749217041), (<aiohttp.client_proto.ResponseHandler object at 0x1115c5970>, 360813.750184041), (<aiohttp.client_proto.ResponseHandler object at 0x1115c6db0>, 360813.750911541), (<aiohttp.client_proto.ResponseHandler object at 0x1115c52b0>, 360813.751859583), (<aiohttp.client_proto.ResponseHandler object at 0x1115c7230>, 360813.7525925), (<aiohttp.client_proto.ResponseHandler object at 0x1115c68d0>, 360813.753415375), (<aiohttp.client_proto.ResponseHandler object at 0x1154a81d0>, 360813.754334541), (<aiohttp.client_proto.ResponseHandler object at 0x1154a83b0>, 360813.755078833), (<aiohttp.client_proto.ResponseHandler object at 0x1115c5e50>, 360813.755983083), (<aiohttp.client_proto.ResponseHandler object at 0x1154a90d0>, 360813.756900625), (<aiohttp.client_proto.ResponseHandler object at 0x1154a8590>, 360813.757711083), (<aiohttp.client_proto.ResponseHandler object at 0x1154a8950>, 360813.758534833), (<aiohttp.client_proto.ResponseHandler object at 0x1113f0d70>, 360813.759515916), (<aiohttp.client_proto.ResponseHandler object at 0x1154a8770>, 360813.760249166), (<aiohttp.client_proto.ResponseHandler object at 0x115458a10>, 360813.763182125), (<aiohttp.client_proto.ResponseHandler object at 0x115458590>, 360813.764108125), (<aiohttp.client_proto.ResponseHandler object at 0x11545b950>, 360813.7652015), (<aiohttp.client_proto.ResponseHandler object at 0x1154a8b30>, 360813.76607425), (<aiohttp.client_proto.ResponseHandler object at 0x115459010>, 360813.766865041), (<aiohttp.client_proto.ResponseHandler object at 0x1154a8d10>, 360813.767758666), (<aiohttp.client_proto.ResponseHandler object at 0x115458dd0>, 360813.769322458), (<aiohttp.client_proto.ResponseHandler object at 0x1154a8ef0>, 360813.770214958), (<aiohttp.client_proto.ResponseHandler object at 0x115459610>, 360813.771062208), (<aiohttp.client_proto.ResponseHandler object at 0x1154597f0>, 360813.772085791), (<aiohttp.client_proto.ResponseHandler object at 0x115459a30>, 360813.772981083), (<aiohttp.client_proto.ResponseHandler object at 0x11545a990>, 360813.7745345), (<aiohttp.client_proto.ResponseHandler object at 0x11545b1d0>, 360813.775449375), (<aiohttp.client_proto.ResponseHandler object at 0x115459bb0>, 360813.776303375), (<aiohttp.client_proto.ResponseHandler object at 0x11545a930>, 360813.777227416), (<aiohttp.client_proto.ResponseHandler object at 0x11545ab70>, 360813.778304833), (<aiohttp.client_proto.ResponseHandler object at 0x11545b410>, 360813.782172791), (<aiohttp.client_proto.ResponseHandler object at 0x11545adb0>, 360813.782955833), (<aiohttp.client_proto.ResponseHandler object at 0x11545aff0>, 360813.783742708), (<aiohttp.client_proto.ResponseHandler object at 0x11545a750>, 360813.788846375), (<aiohttp.client_proto.ResponseHandler object at 0x115459f10>, 360813.789656958), (<aiohttp.client_proto.ResponseHandler object at 0x11545b650>, 360813.790624541), (<aiohttp.client_proto.ResponseHandler object at 0x11545bad0>, 360813.791410916), (<aiohttp.client_proto.ResponseHandler object at 0x11545a810>, 360813.792941166), (<aiohttp.client_proto.ResponseHandler object at 0x11545bcb0>, 360813.793695291), (<aiohttp.client_proto.ResponseHandler object at 0x11545bf50>, 360813.7946535), (<aiohttp.client_proto.ResponseHandler object at 0x1111a71d0>, 360813.795440375), (<aiohttp.client_proto.ResponseHandler object at 0x1111a6cf0>, 360813.796230125), (<aiohttp.client_proto.ResponseHandler object at 0x1111a61b0>, 360813.79702725), (<aiohttp.client_proto.ResponseHandler object at 0x111333470>, 360813.802959291), (<aiohttp.client_proto.ResponseHandler object at 0x1113339b0>, 360813.803241375), (<aiohttp.client_proto.ResponseHandler object at 0x111333bf0>, 360813.804015708)]']
connector: <aiohttp.connector.TCPConnector object at 0x1111e61b0>

Redirects: 412, Norms: 0, IDs: 412, Existing: 20

,Alex Yee,Jordan Chiles,Imane Khelif,Donald J. Harris,India at the 2024 Summer Olympics,Léon Marchand,Hamas,Assassination of Ismail Haniyeh,Cleopatra,Lists of deaths by year
2017-07-01,0,12,0,0,0,0,1669,0,5813,92659
2017-07-02,0,15,0,0,0,0,2119,0,6657,101430
2017-07-03,0,8,0,0,0,0,2715,0,6456,123675
2017-07-04,0,11,0,0,0,0,3375,0,5972,116940
2017-07-05,0,7,0,0,0,0,3630,0,6197,119430