# Clickstream Demo

We demo 2 different functions for collecting clickstream data from Wikipedia:
1. `get_clickstreams` - for collecting different types of clickstream from a list of pages.
2. `pipeline_get_clickstreams` - A convenience wrapper function that, in addition to the above, also sets up session and redirect maps.

## Setup

In [1]:
import wikitoolkit
import pandas as pd

my_agent = 'mwapi testing <p.gildersleve@exeter.ac.uk>'
wtsession = wikitoolkit.WTSession('en.wikipedia', user_agent=my_agent)
toparts = pd.read_csv('data/topviews-2024_07_31.csv')
artlist = toparts['Page'].unique().tolist() # ~1000 top articles yesterday
pagemaps = wikitoolkit.PageMaps()

In [2]:
cs = await wikitoolkit.get_clickstreams(wtsession, titles=artlist[:10], pagemaps=pagemaps,
                           date='2022-05-12', consolidate_redirects=True)
cs

[{'prev': '117th United States Congress',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 267},
 {'prev': '118th United States Congress',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 82},
 {'prev': '11th Streamy Awards',
  'curr': 'Sunisa Lee',
  'type': 'link',
  'n_2022-05': 23},
 {'prev': '131st IOC Session',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 13},
 {'prev': '1896 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '1900 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '1924 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 50},
 {'prev': '1924 Winter Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '1928 United States presidential election',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 15},
 {'prev': '1948 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 48},
 {'prev': '1964', 'curr': 'Kamala Harris', 'type': 'link', 'n_2022-05': 21},
 {'prev': '1972 Summer Olympics',
  'curr': 'Michael Phelps',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '1984 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '1985', 'curr': 'Michael Phelps', 'type': 'link', 'n_2022-05': 21},
 {'prev': '1992 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 38},
 {'prev': '1992 Winter Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '1996 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 13},
 {'prev': '1997', 'curr': 'Katie Ledecky', 'type': 'link', 'n_2022-05': 39},
 {'prev': '1997', 'curr': 'Simone Biles', 'type': 'link', 'n_2022-05': 41},
 {'prev': '2000 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2003', 'curr': 'Sunisa Lee', 'type': 'link', 'n_2022-05': 79},
 {'prev': '2006 Palestinian legislative election',
  'curr': 'Ismail Haniyeh',
  'type': 'link',
  'n_2022-05': 211},
 {'prev': '2008 California Proposition 8',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '2008 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2008 Summer Olympics',
  'curr': 'Michael Phelps',
  'type': 'link',
  'n_2022-05': 17},
 {'prev': '2010 California Attorney General election',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 43},
 {'prev': '2012 Gaza War',
  'curr': 'Ismail Haniyeh',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2012 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 38},
 {'prev': '2012 Summer Olympics',
  'curr': 'Michael Phelps',
  'type': 'link',
  'n_2022-05': 78},
 {'prev': '2012 Summer Olympics medal table',
  'curr': 'Michael Phelps',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2012 United States Olympic trials (swimming)',
  'curr': 'Katie Ledecky',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2013 World Artistic Gymnastics Championships',
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 13},
 {'prev': '2014 California Attorney General election',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 13},
 {'prev': '2014 Gaza War',
  'curr': 'Ismail Haniyeh',
  'type': 'link',
  'n_2022-05': 92},
 {'prev': '2014 World Artistic Gymnastics Championships',
  'curr': 'MyKayla Skinner',
  'type': 'link',
  'n_2022-05': 21},
 {'prev': '2014 World Artistic Gymnastics Championships',
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 16},
 {'prev': '2015 World Artistic Gymnastics Championships',
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 34},
 {'prev': '2016 Democratic Party vice presidential candidate selection',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 26},
 {'prev': '2016 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2016 United States Olympic trials (gymnastics)',
  'curr': 'MyKayla Skinner',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2016 United States Senate election in California',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 154},
 {'prev': '2016 United States Senate elections',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2018 World Artistic Gymnastics Championships',
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 32},
 {'prev': '2019 Gaza economic protests',
  'curr': 'Ismail Haniyeh',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '2019 World Artistic Gymnastics Championships',
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 50},
 {'prev': '2019 World Artistic Gymnastics Championships',
  'curr': 'Sunisa Lee',
  'type': 'link',
  'n_2022-05': 34},
 {'prev': '2020 Democratic National Convention',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 53},
 {'prev': '2020 Democratic Party presidential candidates',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 24},
 {'prev': '2020 Democratic Party presidential debates',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 11},
 {'prev': '2020 Democratic Party presidential primaries',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 141},
 {'prev': '2020 Democratic Party vice presidential candidate selection',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 58},
 {'prev': '2020 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 8824},
 {'prev': '2020 Summer Olympics Parade of Nations',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2020 Summer Olympics closing ceremony',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 27},
 {'prev': '2020 Summer Olympics marketing',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 11},
 {'prev': '2020 Summer Olympics medal table',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 335},
 {'prev': '2020 Summer Olympics opening ceremony',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '2020 United States Olympic trials (gymnastics)',
  'curr': 'MyKayla Skinner',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2020 United States Olympic trials (gymnastics)',
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 13},
 {'prev': '2020 United States Olympic trials (gymnastics)',
  'curr': 'Sunisa Lee',
  'type': 'link',
  'n_2022-05': 24},
 {'prev': '2020 United States Olympic trials (swimming)',
  'curr': 'Katie Ledecky',
  'type': 'link',
  'n_2022-05': 15},
 {'prev': '2020 United States elections',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 11},
 {'prev': '2020 United States presidential debates',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 15},
 {'prev': '2020 United States presidential election',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 1987},
 {'prev': '2020 United States presidential election in Arizona',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 19},
 {'prev': '2020 United States presidential election in California',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 29},
 {'prev': '2020 United States presidential election in Florida',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 19},
 {'prev': '2020 United States presidential election in Georgia',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 45},
 {'prev': '2020 United States presidential election in Michigan',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '2020 United States presidential election in New York',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 23},
 {'prev': '2020 United States presidential election in North Carolina',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 11},
 {'prev': '2020 United States presidential election in Pennsylvania',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 22},
 {'prev': '2020 United States presidential election in South Carolina',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2020 United States presidential election in Tennessee',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2020 United States presidential election in Texas',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 34},
 {'prev': '2020 United States presidential election in Virginia',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2020 United States presidential election in Wisconsin',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '2020–21 United States Senate election in Georgia',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 11},
 {'prev': '2021 Atlanta spa shootings',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 11},
 {'prev': '2021 BBC Sports Personality of the Year Award',
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 20},
 {'prev': '2021 Israel–Palestine crisis',
  'curr': 'Ismail Haniyeh',
  'type': 'link',
  'n_2022-05': 367},
 {'prev': "2021 Kids' Choice Awards",
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 17},
 {'prev': '2021 U.S. Classic',
  'curr': 'MyKayla Skinner',
  'type': 'link',
  'n_2022-05': 11},
 {'prev': '2021 U.S. National Gymnastics Championships',
  'curr': 'MyKayla Skinner',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2021 U.S. National Gymnastics Championships',
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 26},
 {'prev': '2021 U.S. National Gymnastics Championships',
  'curr': 'Sunisa Lee',
  'type': 'link',
  'n_2022-05': 22},
 {'prev': '2021 United States Electoral College vote count',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 13},
 {'prev': '2022 Asian Games',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 225},
 {'prev': '2022 CONCACAF U-20 Championship',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 218},
 {'prev': '2022 CONCACAF W Championship',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 167},
 {'prev': '2022 Commonwealth Games',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 62},
 {'prev': '2022 FEI World Championships',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2022 Houston Texans season',
  'curr': 'Jonathan Owens',
  'type': 'link',
  'n_2022-05': 66},
 {'prev': "2022 Kids' Choice Awards",
  'curr': 'Simone Biles',
  'type': 'link',
  'n_2022-05': 24},
 {'prev': "2022 NCAA women's gymnastics tournament",
  'curr': 'Sunisa Lee',
  'type': 'link',
  'n_2022-05': 74},
 {'prev': '2022 State of the Union Address',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 16},
 {'prev': '2022 UEFA Champions League final chaos',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 28},
 {'prev': '2022 USA Swimming International Team Trials',
  'curr': 'Katie Ledecky',
  'type': 'link',
  'n_2022-05': 36},
 {'prev': '2022 United States Senate election in New Hampshire',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2022 United States Senate elections',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 278},
 {'prev': '2022 United States Senate elections in California',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 72},
 {'prev': '2022 United States elections',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 159},
 {'prev': '2022 Winter Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 3231},
 {'prev': '2022 Winter Olympics closing ceremony',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 17},
 {'prev': '2022 Winter Olympics opening ceremony',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 13},
 {'prev': '2022 World Aquatics Championships',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 29},
 {'prev': '2022 in the United States',
  'curr': 'Kamala Harris',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2023 European Games',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 65},
 {'prev': '2023 FIBA Basketball World Cup',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 228},
 {'prev': '2023 Pan American Games',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 59},
 {'prev': '2023 Rugby World Cup',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 114},
 {'prev': '2023 UEFA European Under-21 Championship',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 109},
 {'prev': '2024',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 176},
 {'prev': "2024 AFC Women's Olympic Qualifying Tournament",
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 36},
 {'prev': '2024 Summer Olympics',
  'curr': '131st IOC Session',
  'type': 'link',
  'n_2022-05': 145},
 {'prev': '2024 Summer Olympics',
  'curr': '134th IOC Session',
  'type': 'link',
  'n_2022-05': 26},
 {'prev': '2024 Summer Olympics',
  'curr': '1900 Summer Olympics',
  'type': 'link',
  'n_2022-05': 139},
 {'prev': '2024 Summer Olympics',
  'curr': '1908 Summer Olympics',
  'type': 'link',
  'n_2022-05': 42},
 {'prev': '2024 Summer Olympics',
  'curr': '1924 Summer Olympics',
  'type': 'link',
  'n_2022-05': 254},
 {'prev': '2024 Summer Olympics',
  'curr': '1924 Winter Olympics',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2024 Summer Olympics',
  'curr': '1948 Summer Olympics',
  'type': 'link',
  'n_2022-05': 66},
 {'prev': '2024 Summer Olympics',
  'curr': '1968 Winter Olympics',
  'type': 'link',
  'n_2022-05': 31},
 {'prev': '2024 Summer Olympics',
  'curr': '1992 Winter Olympics',
  'type': 'link',
  'n_2022-05': 254},
 {'prev': '2024 Summer Olympics',
  'curr': '1996 Summer Olympics',
  'type': 'link',
  'n_2022-05': 11},
 {'prev': '2024 Summer Olympics',
  'curr': '2003 World Championships in Athletics',
  'type': 'link',
  'n_2022-05': 40},
 {'prev': '2024 Summer Olympics',
  'curr': '2008 Summer Olympics',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '2024 Summer Olympics',
  'curr': '2012 Summer Olympics',
  'type': 'link',
  'n_2022-05': 114},
 {'prev': '2024 Summer Olympics',
  'curr': '2016 Summer Olympics',
  'type': 'link',
  'n_2022-05': 21},
 {'prev': '2024 Summer Olympics',
  'curr': '2020 Summer Olympics',
  'type': 'link',
  'n_2022-05': 4559},
 {'prev': '2024 Summer Olympics',
  'curr': '2020 Summer Olympics closing ceremony',
  'type': 'link',
  'n_2022-05': 34},
 {'prev': '2024 Summer Olympics',
  'curr': '2022 Winter Olympics',
  'type': 'link',
  'n_2022-05': 1593},
 {'prev': '2024 Summer Olympics',
  'curr': '2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 64},
 {'prev': '2024 Summer Olympics',
  'curr': '2024 Summer Paralympics',
  'type': 'link',
  'n_2022-05': 823},
 {'prev': '2024 Summer Olympics',
  'curr': '2024 Winter Youth Olympics',
  'type': 'link',
  'n_2022-05': 179},
 {'prev': '2024 Summer Olympics',
  'curr': '2026 Winter Olympics',
  'type': 'link',
  'n_2022-05': 3934},
 {'prev': '2024 Summer Olympics',
  'curr': '2028 Summer Olympics',
  'type': 'link',
  'n_2022-05': 12788},
 {'prev': '2024 Summer Olympics',
  'curr': '2030 Winter Olympics',
  'type': 'link',
  'n_2022-05': 112},
 {'prev': '2024 Summer Olympics',
  'curr': '2032 Summer Olympics',
  'type': 'link',
  'n_2022-05': 196},
 {'prev': '2024 Summer Olympics',
  'curr': 'Accor',
  'type': 'link',
  'n_2022-05': 16},
 {'prev': '2024 Summer Olympics',
  'curr': 'Accor Arena',
  'type': 'link',
  'n_2022-05': 234},
 {'prev': '2024 Summer Olympics',
  'curr': 'Air France',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '2024 Summer Olympics',
  'curr': 'Airbnb',
  'type': 'link',
  'n_2022-05': 22},
 {'prev': '2024 Summer Olympics',
  'curr': 'Albertville',
  'type': 'link',
  'n_2022-05': 38},
 {'prev': '2024 Summer Olympics',
  'curr': 'Alibaba Group',
  'type': 'link',
  'n_2022-05': 16},
 {'prev': '2024 Summer Olympics',
  'curr': 'Allianz',
  'type': 'link',
  'n_2022-05': 19},
 {'prev': '2024 Summer Olympics',
  'curr': 'Allianz Riviera',
  'type': 'link',
  'n_2022-05': 39},
 {'prev': '2024 Summer Olympics',
  'curr': 'América Móvil',
  'type': 'link',
  'n_2022-05': 29},
 {'prev': '2024 Summer Olympics',
  'curr': 'Art Deco in Paris',
  'type': 'link',
  'n_2022-05': 23},
 {'prev': '2024 Summer Olympics',
  'curr': 'Atos',
  'type': 'link',
  'n_2022-05': 20},
 {'prev': '2024 Summer Olympics',
  'curr': 'BBC',
  'type': 'link',
  'n_2022-05': 21},
 {'prev': '2024 Summer Olympics',
  'curr': 'Bids for the 2024 and 2028 Summer Olympics',
  'type': 'link',
  'n_2022-05': 568},
 {'prev': '2024 Summer Olympics',
  'curr': 'Bids for the 2036 Summer Olympics',
  'type': 'link',
  'n_2022-05': 129},
 {'prev': '2024 Summer Olympics',
  'curr': 'Boat parade',
  'type': 'link',
  'n_2022-05': 31},
 {'prev': '2024 Summer Olympics',
  'curr': 'Bordeaux',
  'type': 'link',
  'n_2022-05': 12},
 {'prev': '2024 Summer Olympics',
  'curr': 'Breakdancing',
  'type': 'link',
  'n_2022-05': 110},
 {'prev': '2024 Summer Olympics',
  'curr': 'Breaking at the 2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 414},
 {'prev': '2024 Summer Olympics',
  'curr': 'Bridgestone',
  'type': 'link',
  'n_2022-05': 16},
 {'prev': '2024 Summer Olympics',
  'curr': 'Budapest bid for the 2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 41},
 {'prev': '2024 Summer Olympics',
  'curr': 'Canadian Broadcasting Corporation',
  'type': 'link',
  'n_2022-05': 16},
 {'prev': '2024 Summer Olympics',
  'curr': 'Champ de Mars',
  'type': 'link',
  'n_2022-05': 187},
 {'prev': '2024 Summer Olympics',
  'curr': 'China Central Television',
  'type': 'link',
  'n_2022-05': 22},
 {'prev': '2024 Summer Olympics',
  'curr': 'Cook Islands',
  'type': 'link',
  'n_2022-05': 14},
 {'prev': '2024 Summer Olympics',
  'curr': 'DXC Technology',
  'type': 'link',
  'n_2022-05': 18},
 {'prev': '2024 Summer Olympics',
  'curr': 'Decathlon (retailer)',
  'type': 'link',
  'n_2022-05': 26},
 {'prev': '2024 Summer Olympics',
  'curr': 'Dentsu',
  'type': 'link',
  'n_2022-05': 73},
 {'prev': '2024 Summer Olympics',
  'curr': 'Discovery, Inc.',
  'type': 'link',
  'n_2022-05': 18},
 {'prev': '2024 Summer Olympics',
  'curr': 'Emmanuel Macron',
  'type': 'link',
  'n_2022-05': 745},
 {'prev': '2024 Summer Olympics',
  'curr': 'Esports',
  'type': 'link',
  'n_2022-05': 26},
 {'prev': '2024 Summer Olympics',
  'curr': 'Eurosport',
  'type': 'link',
  'n_2022-05': 43},
 {'prev': '2024 Summer Olympics',
  'curr': 'Field hockey at the 2024 Summer Olympics',
  'type': 'link',
  'n_2022-05': 2851},
 {'prev': '2024 Summer Olympics',
  'curr': 'France Télévisions',
  'type': 'link',
  'n_2022-05': 39},
 {'prev': '2024 Summer Olympics',
  'curr': 'Française des Jeux (lottery)',
  'type': 'link',
  'n_2022-05': 13},
 {'prev': '2024 Summer Olympics',
  'curr': 'French Polynesia',
  'type': 'link',
  'n_2022-05': 154},
 {'prev': '2024 Summer Olympics',
  'curr': 'French language',
  'type': 'link',
  'n_2022-05': 38},
 {'prev': '2024 Summer Olympics',
  'curr': 'General Electric',
  'type': 'link',
  'n_2022-05': 10},
 {'prev': '2024 Summer Olympics',
  'curr': 'Grand Palais',
  'type': 'link',
  'n_2022-05': 175},
 {'prev': '2024 Summer Olympics',
  'curr': 'Grand Palais Éphémère',
  'type': 'link',
  'n_2022-05': 120},
 {'prev': '2024 Summer Olympics',
  'curr': 'Grand Rex',
  'type': 'link',
  'n_2022-05': 20},
 {'prev': '2024 Summer Olympics',
  'curr': 'Groupe BPCE',
  'type': 'link',
  'n_2022-05': 15},
 {'prev': '2024 Summer Olympics',
  'curr': 'Grupo Globo',
  'type': 'link',
  'n_2022-05': 12},

In [4]:
cs = await wikitoolkit.get_clickstreams(wtsession, titles=artlist[:10], pagemaps=pagemaps,
                           date='2022-05-12', consolidate_redirects=False)
pd.DataFrame(cs)

                              prev                  curr  type  n_2022-05
0     117th United States Congress         Kamala Harris  link        267
1     118th United States Congress         Kamala Harris  link         82
2              11th Streamy Awards            Sunisa Lee  link         23
3                131st IOC Session  2024 Summer Olympics  link         13
4             1896 Summer Olympics  2024 Summer Olympics  link         10
...                            ...                   ...   ...        ...
1797                  Yahya Sinwar        Ismail Haniyeh  link        925
1798                          Yips          Simone Biles  link         73
1799             Yurchenko (vault)          Simone Biles  link         14
1800               Zinedine Zidane  2024 Summer Olympics  link         24
1801                  Ziwe Fumudoh         Kamala Harris  link         20

[1802 rows x 4 columns]

In [6]:
cs = await wikitoolkit.get_clickstreams(wtsession, titles=artlist[:10], pagemaps=pagemaps,
                           daterange=('2022-05-12', '2022-06-13'), consolidate_redirects=True)
pd.DataFrame(cs)

,prev,curr,type,n_2022-05,n_2022-06
0,117th United States Congress,Kamala Harris,link,267.0,279.0
1,118th United States Congress,Kamala Harris,link,82.0,73.0
2,11th Streamy Awards,Sunisa Lee,link,23.0,13.0
3,131st IOC Session,2024 Summer Olympics,link,13.0,12.0
4,1896 Summer Olympics,2024 Summer Olympics,link,10.0,NaN
...,...,...,...,...,...
2191,Yahya Sinwar,Ismail Haniyeh,link,925.0,90.0
2192,Yips,Simone Biles,link,73.0,58.0
2193,Yurchenko vault family,Simone Biles,link,14.0,NaN
2194,Zinedine Zidane,2024 Summer Olympics,link,24.0,17.0
2195,Ziwe Fumudoh,Kamala Harris,link,20.0,16.0

In [2]:
cs = await wikitoolkit.pipeline_get_clickstreams('en.wikipedia', my_agent, titles=artlist[:10], pagemaps=pagemaps,
                             gc_args={'date':'2022-05-12'})

pd.DataFrame(cs)

                              prev                  curr  type  n_2022-05
0     117th United States Congress         Kamala Harris  link        267
1     118th United States Congress         Kamala Harris  link         82
2              11th Streamy Awards            Sunisa Lee  link         23
3                131st IOC Session  2024 Summer Olympics  link         13
4             1896 Summer Olympics  2024 Summer Olympics  link         10
...                            ...                   ...   ...        ...
1794                  Yahya Sinwar        Ismail Haniyeh  link        925
1795                          Yips          Simone Biles  link         73
1796        Yurchenko vault family          Simone Biles  link         14
1797               Zinedine Zidane  2024 Summer Olympics  link         24
1798                  Ziwe Fumudoh         Kamala Harris  link         20

[1799 rows x 4 columns]

In [ ]:
import os
datapath = 'data/'
lang = 'en'
monthlist = pd.date_range('2019-12-01', '2024-12-01', freq='MS').strftime('%Y-%m').tolist()
for ym in monthlist:
    urlpath = f'https://dumps.wikimedia.org/other/clickstream/{ym}/clickstream-{lang}wiki-{ym}.tsv.gz'
    if not os.path.exists(datapath):
        os.makedirs(datapath)
    if not os.path.exists(f'{datapath}clickstream-{lang}wiki-{ym}.tsv.gz'):
        print(f'Downloading clickstream data for {ym}...')
        wikitoolkit.download_large_file(urlpath, f'{datapath}clickstream-{lang}wiki-{ym}.tsv.gz')

Downloading clickstream data for 2020-01...
Starting download: https://dumps.wikimedia.org/other/clickstream/2020-01/clickstream-enwiki-2020-01.tsv.gz
Downloaded 410800911/410800911 bytes (100.00%)
Download completed.
Downloading clickstream data for 2020-02...
Starting download: https://dumps.wikimedia.org/other/clickstream/2020-02/clickstream-enwiki-2020-02.tsv.gz
Downloaded 385304570/385304570 bytes (100.00%)
Download completed.
Downloading clickstream data for 2020-03...
Starting download: https://dumps.wikimedia.org/other/clickstream/2020-03/clickstream-enwiki-2020-03.tsv.gz
Downloaded 387956391/387956391 bytes (100.00%)
Download completed.
Downloading clickstream data for 2020-04...
Starting download: https://dumps.wikimedia.org/other/clickstream/2020-04/clickstream-enwiki-2020-04.tsv.gz
Downloaded 431146810/431146810 bytes (100.00%)
Download completed.
Downloading clickstream data for 2020-05...
Starting download: https://dumps.wikimedia.org/other/clickstream/2020-05/clickstream-enwiki-2020-05.tsv.gz
Downloaded 429659007/429659007 bytes (100.00%)
Download completed.
Downloading clickstream data for 2020-06...
Starting download: https://dumps.wikimedia.org/other/clickstream/2020-06/clickstream-enwiki-2020-06.tsv.gz
Downloaded 378645793/378645793 bytes (100.00%)
Download completed.
Downloading clickstream data for 2020-07...
Starting download: https://dumps.wikimedia.org/other/clickstream/2020-07/clickstream-enwiki-2020-07.tsv.gz
Downloaded 348127232/387270325 bytes (89.89%)

## `get_clickstreams`

This can be used to collect clickstream navigational data to/from a list of articles.

### Out-links

In [ ]:
outlinks = await wikitoolkit.get_links(wtsession, mode='out', titles=artlist[:10])
edges = pd.DataFrame(set([(k, x['title']) for k, v in outlinks.items() for x in v]),
            columns=['source', 'target'])
edges

Warning: No PageMaps object provided, this is not recommended practice
Getting out-links

                    source                                        target
0           Michael Phelps                                    Dan Veatch
1           Michael Phelps                              Malcolm Champion
2            Kamala Harris                                   Deb Haaland
3            Kamala Harris                              Choctaw freedmen
4               Sunisa Lee        Michigan Wolverines women's gymnastics
...                    ...                                           ...
9770  2024 Summer Olympics  Papua New Guinea at the 2024 Summer Olympics
9771         Kamala Harris                         Governor of Minnesota
9772  Deadpool & Wolverine                                 Jemma Simmons
9773          Simone Biles                            The New York Times
9774       MyKayla Skinner                            Tiana Sumanasekera

[9775 rows x 2 columns]